"""Transformation audit trail + data-quality summary.

Every value the pipeline changes, and every QC flag it raises, is appended here
as a structured event. This is the "show your work" layer: it makes the demo
trustworthy (nothing happens silently) and is itself exportable as an artifact.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from collections import Counter
from datetime import datetime, timezone
from typing import Optional


@dataclass
class AuditEvent:
    action: str                      # "normalize" | "flag" | "map" | "drop"
    field_name: Optional[str] = None
    well: Optional[str] = None
    rule: Optional[str] = None       # the rule / flag code
    severity: str = "info"           # "info" | "warn" | "error"
    before: Optional[str] = None
    after: Optional[str] = None
    detail: str = ""

    def as_dict(self) -> dict:
        return asdict(self)


@dataclass
class AuditLog:
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    events: list[AuditEvent] = field(default_factory=list)

    def record(self, action: str, **kwargs) -> None:
        self.events.append(AuditEvent(action=action, **kwargs))

    # convenience wrappers used by normalize/qc -----------------------------
    def normalized(self, field_name, well, before, after, detail, rule="NORMALIZED"):
        self.record("normalize", field_name=field_name, well=well, rule=rule,
                    severity="info", before=str(before), after=str(after), detail=detail)

    def flag(self, code, well, severity="warn", detail="", field_name=None):
        self.record("flag", field_name=field_name, well=well, rule=code,
                    severity=severity, detail=detail)

    # reporting --------------------------------------------------------------
    def flags(self) -> list[AuditEvent]:
        return [e for e in self.events if e.action == "flag"]

    def flag_counts(self) -> dict[str, int]:
        return dict(Counter(e.rule for e in self.flags()))

    def severity_counts(self) -> dict[str, int]:
        return dict(Counter(e.severity for e in self.flags()))

    def to_records(self) -> list[dict]:
        return [e.as_dict() for e in self.events]

    def to_json(self, indent: int = 2) -> str:
        return json.dumps({"created_at": self.created_at, "events": self.to_records()},
                          indent=indent)


def build_summary(audit: AuditLog, rows_in: int, rows_out: int,
                  mappings: list, required_present: bool) -> dict:
    """Assemble the one-page data-quality summary (machine-readable)."""
    auto = sum(1 for m in mappings if getattr(m, "bucket", None) == "auto" and not getattr(m, "locked", False))
    manual = sum(1 for m in mappings if getattr(m, "locked", False))
    review = sum(1 for m in mappings if getattr(m, "bucket", None) == "review")
    unmapped = sum(1 for m in mappings if getattr(m, "bucket", None) == "unmapped")

    flag_counts = audit.flag_counts()
    sev = audit.severity_counts()
    wells_flagged = len({e.well for e in audit.flags() if e.well})

    return {
        "rows_in": rows_in,
        "rows_out": rows_out,
        "rows_dropped": rows_in - rows_out,
        "columns_auto_mapped": auto,
        "columns_manually_mapped": manual,
        "columns_needing_review": review,
        "columns_unmapped": unmapped,
        "required_fields_present": required_present,
        "normalizations": sum(1 for e in audit.events if e.action == "normalize"),
        "total_flags": len(audit.flags()),
        "flags_by_type": flag_counts,
        "flags_by_severity": sev,
        "wells_flagged": wells_flagged,
        "ml_ready": required_present and sev.get("error", 0) == 0,
    }


def summary_to_markdown(summary: dict) -> str:
    lines = [
        "# LabBridge Data-Quality Summary",
        "",
        f"- Rows in: **{summary['rows_in']}**  ->  Rows out: **{summary['rows_out']}** "
        f"(dropped {summary['rows_dropped']})",
        f"- Columns: {summary['columns_auto_mapped']} auto-mapped, "
        f"{summary['columns_manually_mapped']} manual, "
        f"{summary['columns_needing_review']} need review, "
        f"{summary['columns_unmapped']} unmapped",
        f"- Required fields present: **{summary['required_fields_present']}**",
        f"- Normalizations applied: **{summary['normalizations']}**",
        f"- QC flags: **{summary['total_flags']}** across "
        f"**{summary['wells_flagged']}** wells",
        "",
        "## Flags by type",
    ]
    for code, n in sorted(summary["flags_by_type"].items(), key=lambda kv: -kv[1]):
        lines.append(f"- `{code}`: {n}")
    lines += [
        "",
        f"## ML-ready: {'YES' if summary['ml_ready'] else 'NO'}",
        "",
        "_Generated by LabBridge. Every change is recorded in the transformation log._",
    ]
    return "\n".join(lines)
